### ISSUE TITLE
-ErrorAction SilentlyContinue  is not honoured

### ISSUE THREAD

**Issue by lukeb1961** [igoravl/TfsCmdlets#125]
Get-TfsTeamProject 
Get-TfsWorkItem 

both still show red error (access denied) despite using -ErrorAction SilentlyContinue

**Comment by lukeb1961** [comment]
PS C:\Users\lukeb> $error[0].Exception.StackTrace
   at TfsCmdlets.Extensions.TaskExtensions.GetResult[T](Task`1 task, String errorMessage)
   at TfsCmdlets.Cmdlets.TeamProject.TeamProjectDataService.<DoGetItems>d__0.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at TfsCmdlets.Services.BaseDataService`1.GetItem()
   at TfsCmdlets.Services.CmdletServiceProviderImpl.GetCollectionAndProject(CmdletBase cmdlet, ParameterDictionary parameters)
   at TfsCmdlets.Cmdlets.WorkItem.WorkItemDataService.<DoGetItems>d__0.MoveNext()
   at System.Management.Automation.MshCommandRuntime._WriteObjectsSkipAllowCheck(Object sendToPipeline)
   at System.Security.SecurityContext.Run(SecurityContext securityContext, ContextCallback callback, Object state)
   at System.Management.Automation.MshCommandRuntime.WriteObject(Object sendToPipeline, Boolean enumerateCollection)
   at System.Management.Automation.Cmdlet.WriteObject(Object sendToPipeline, Boolean enumerateCollection)
   at System.Management.Automation.CommandProcessor.ProcessRecord()

**Comment by igoravl** [comment]
Good catch, @lukeb1961 . Presently, all errors caught by TfsCmdlets as _terminating errors_, but I agree that commands that handle multiple inputs and/or outputs should use _non-terminating errors_ instead, so that a caller can use ErrorAction and determine the best course of action.

I plan on implement this pattern, but honestly I can't define a clear roadmap now. I'd expect it to take a couple months at least, until I have the chance to work on this issue. Stay tuned :-)

Now, for future reference (when the time comes to implement this:

https://stackoverflow.com/a/39949027
